namespace PrintTrack.Forms.F_Perfil
{
    partial class Perfil_Frm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Perfil_Frm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuShadowPanel3 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.btnFinTurno = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnIniciarTurno = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuShadowPanel2 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.pbImagen = new System.Windows.Forms.PictureBox();
            this.btnGuardarCambios = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtNombreCompleto = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtNombreUsuario = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTelefono = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnEditarClave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnEditarUsuario = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblUltimoAcceso = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuGradientPanel1.SuspendLayout();
            this.bunifuShadowPanel3.SuspendLayout();
            this.bunifuShadowPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbImagen)).BeginInit();
            this.bunifuShadowPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.bunifuShadowPanel3);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuShadowPanel2);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuShadowPanel1);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.White;
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.White;
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.DodgerBlue;
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.White;
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(1144, 675);
            this.bunifuGradientPanel1.TabIndex = 1;
            // 
            // bunifuShadowPanel3
            // 
            this.bunifuShadowPanel3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel3.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel3.BorderRadius = 10;
            this.bunifuShadowPanel3.BorderThickness = 1;
            this.bunifuShadowPanel3.Controls.Add(this.btnFinTurno);
            this.bunifuShadowPanel3.Controls.Add(this.btnIniciarTurno);
            this.bunifuShadowPanel3.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel3.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel3.Location = new System.Drawing.Point(566, 12);
            this.bunifuShadowPanel3.Name = "bunifuShadowPanel3";
            this.bunifuShadowPanel3.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel3.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel3.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel3.ShadowDept = 2;
            this.bunifuShadowPanel3.ShadowDepth = 5;
            this.bunifuShadowPanel3.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel3.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel3.Size = new System.Drawing.Size(566, 106);
            this.bunifuShadowPanel3.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel3.TabIndex = 3;
            // 
            // btnFinTurno
            // 
            this.btnFinTurno.AllowAnimations = true;
            this.btnFinTurno.AllowMouseEffects = true;
            this.btnFinTurno.AllowToggling = false;
            this.btnFinTurno.AnimationSpeed = 200;
            this.btnFinTurno.AutoGenerateColors = false;
            this.btnFinTurno.AutoRoundBorders = false;
            this.btnFinTurno.AutoSizeLeftIcon = true;
            this.btnFinTurno.AutoSizeRightIcon = true;
            this.btnFinTurno.BackColor = System.Drawing.Color.Transparent;
            this.btnFinTurno.BackColor1 = System.Drawing.Color.Crimson;
            this.btnFinTurno.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnFinTurno.BackgroundImage")));
            this.btnFinTurno.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFinTurno.ButtonText = "Terminar Turno";
            this.btnFinTurno.ButtonTextMarginLeft = 0;
            this.btnFinTurno.ColorContrastOnClick = 45;
            this.btnFinTurno.ColorContrastOnHover = 45;
            this.btnFinTurno.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnFinTurno.CustomizableEdges = borderEdges1;
            this.btnFinTurno.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFinTurno.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFinTurno.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFinTurno.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFinTurno.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnFinTurno.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnFinTurno.ForeColor = System.Drawing.Color.White;
            this.btnFinTurno.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFinTurno.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnFinTurno.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnFinTurno.IconMarginLeft = 11;
            this.btnFinTurno.IconPadding = 10;
            this.btnFinTurno.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnFinTurno.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnFinTurno.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnFinTurno.IconSize = 25;
            this.btnFinTurno.IdleBorderColor = System.Drawing.Color.Crimson;
            this.btnFinTurno.IdleBorderRadius = 10;
            this.btnFinTurno.IdleBorderThickness = 1;
            this.btnFinTurno.IdleFillColor = System.Drawing.Color.Crimson;
            this.btnFinTurno.IdleIconLeftImage = null;
            this.btnFinTurno.IdleIconRightImage = null;
            this.btnFinTurno.IndicateFocus = false;
            this.btnFinTurno.Location = new System.Drawing.Point(321, 17);
            this.btnFinTurno.Name = "btnFinTurno";
            this.btnFinTurno.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFinTurno.OnDisabledState.BorderRadius = 10;
            this.btnFinTurno.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFinTurno.OnDisabledState.BorderThickness = 1;
            this.btnFinTurno.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFinTurno.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFinTurno.OnDisabledState.IconLeftImage = null;
            this.btnFinTurno.OnDisabledState.IconRightImage = null;
            this.btnFinTurno.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnFinTurno.onHoverState.BorderRadius = 10;
            this.btnFinTurno.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFinTurno.onHoverState.BorderThickness = 1;
            this.btnFinTurno.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnFinTurno.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnFinTurno.onHoverState.IconLeftImage = null;
            this.btnFinTurno.onHoverState.IconRightImage = null;
            this.btnFinTurno.OnIdleState.BorderColor = System.Drawing.Color.Crimson;
            this.btnFinTurno.OnIdleState.BorderRadius = 10;
            this.btnFinTurno.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFinTurno.OnIdleState.BorderThickness = 1;
            this.btnFinTurno.OnIdleState.FillColor = System.Drawing.Color.Crimson;
            this.btnFinTurno.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnFinTurno.OnIdleState.IconLeftImage = null;
            this.btnFinTurno.OnIdleState.IconRightImage = null;
            this.btnFinTurno.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnFinTurno.OnPressedState.BorderRadius = 10;
            this.btnFinTurno.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFinTurno.OnPressedState.BorderThickness = 1;
            this.btnFinTurno.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnFinTurno.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnFinTurno.OnPressedState.IconLeftImage = null;
            this.btnFinTurno.OnPressedState.IconRightImage = null;
            this.btnFinTurno.Size = new System.Drawing.Size(220, 70);
            this.btnFinTurno.TabIndex = 18;
            this.btnFinTurno.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnFinTurno.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnFinTurno.TextMarginLeft = 0;
            this.btnFinTurno.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnFinTurno.UseDefaultRadiusAndThickness = true;
            // 
            // btnIniciarTurno
            // 
            this.btnIniciarTurno.AllowAnimations = true;
            this.btnIniciarTurno.AllowMouseEffects = true;
            this.btnIniciarTurno.AllowToggling = false;
            this.btnIniciarTurno.AnimationSpeed = 200;
            this.btnIniciarTurno.AutoGenerateColors = false;
            this.btnIniciarTurno.AutoRoundBorders = false;
            this.btnIniciarTurno.AutoSizeLeftIcon = true;
            this.btnIniciarTurno.AutoSizeRightIcon = true;
            this.btnIniciarTurno.BackColor = System.Drawing.Color.Transparent;
            this.btnIniciarTurno.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnIniciarTurno.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnIniciarTurno.BackgroundImage")));
            this.btnIniciarTurno.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnIniciarTurno.ButtonText = "Empezar Turno";
            this.btnIniciarTurno.ButtonTextMarginLeft = 0;
            this.btnIniciarTurno.ColorContrastOnClick = 45;
            this.btnIniciarTurno.ColorContrastOnHover = 45;
            this.btnIniciarTurno.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnIniciarTurno.CustomizableEdges = borderEdges2;
            this.btnIniciarTurno.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnIniciarTurno.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnIniciarTurno.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnIniciarTurno.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnIniciarTurno.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnIniciarTurno.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnIniciarTurno.ForeColor = System.Drawing.Color.White;
            this.btnIniciarTurno.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnIniciarTurno.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnIniciarTurno.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnIniciarTurno.IconMarginLeft = 11;
            this.btnIniciarTurno.IconPadding = 10;
            this.btnIniciarTurno.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnIniciarTurno.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnIniciarTurno.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnIniciarTurno.IconSize = 25;
            this.btnIniciarTurno.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnIniciarTurno.IdleBorderRadius = 10;
            this.btnIniciarTurno.IdleBorderThickness = 1;
            this.btnIniciarTurno.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnIniciarTurno.IdleIconLeftImage = null;
            this.btnIniciarTurno.IdleIconRightImage = null;
            this.btnIniciarTurno.IndicateFocus = false;
            this.btnIniciarTurno.Location = new System.Drawing.Point(27, 17);
            this.btnIniciarTurno.Name = "btnIniciarTurno";
            this.btnIniciarTurno.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnIniciarTurno.OnDisabledState.BorderRadius = 10;
            this.btnIniciarTurno.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnIniciarTurno.OnDisabledState.BorderThickness = 1;
            this.btnIniciarTurno.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnIniciarTurno.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnIniciarTurno.OnDisabledState.IconLeftImage = null;
            this.btnIniciarTurno.OnDisabledState.IconRightImage = null;
            this.btnIniciarTurno.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnIniciarTurno.onHoverState.BorderRadius = 10;
            this.btnIniciarTurno.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnIniciarTurno.onHoverState.BorderThickness = 1;
            this.btnIniciarTurno.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnIniciarTurno.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnIniciarTurno.onHoverState.IconLeftImage = null;
            this.btnIniciarTurno.onHoverState.IconRightImage = null;
            this.btnIniciarTurno.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnIniciarTurno.OnIdleState.BorderRadius = 10;
            this.btnIniciarTurno.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnIniciarTurno.OnIdleState.BorderThickness = 1;
            this.btnIniciarTurno.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnIniciarTurno.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnIniciarTurno.OnIdleState.IconLeftImage = null;
            this.btnIniciarTurno.OnIdleState.IconRightImage = null;
            this.btnIniciarTurno.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnIniciarTurno.OnPressedState.BorderRadius = 10;
            this.btnIniciarTurno.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnIniciarTurno.OnPressedState.BorderThickness = 1;
            this.btnIniciarTurno.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnIniciarTurno.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnIniciarTurno.OnPressedState.IconLeftImage = null;
            this.btnIniciarTurno.OnPressedState.IconRightImage = null;
            this.btnIniciarTurno.Size = new System.Drawing.Size(274, 70);
            this.btnIniciarTurno.TabIndex = 17;
            this.btnIniciarTurno.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnIniciarTurno.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnIniciarTurno.TextMarginLeft = 0;
            this.btnIniciarTurno.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnIniciarTurno.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuShadowPanel2
            // 
            this.bunifuShadowPanel2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel2.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel2.BorderRadius = 10;
            this.bunifuShadowPanel2.BorderThickness = 1;
            this.bunifuShadowPanel2.Controls.Add(this.pbImagen);
            this.bunifuShadowPanel2.Controls.Add(this.btnGuardarCambios);
            this.bunifuShadowPanel2.Controls.Add(this.txtNombreCompleto);
            this.bunifuShadowPanel2.Controls.Add(this.txtNombreUsuario);
            this.bunifuShadowPanel2.Controls.Add(this.txtEmail);
            this.bunifuShadowPanel2.Controls.Add(this.txtTelefono);
            this.bunifuShadowPanel2.Controls.Add(this.btnEditarClave);
            this.bunifuShadowPanel2.Controls.Add(this.btnEditarUsuario);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuLabel9);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuLabel8);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuLabel5);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuLabel7);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuLabel6);
            this.bunifuShadowPanel2.Controls.Add(this.lblUltimoAcceso);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuLabel3);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuLabel2);
            this.bunifuShadowPanel2.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel2.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel2.Location = new System.Drawing.Point(12, 124);
            this.bunifuShadowPanel2.Name = "bunifuShadowPanel2";
            this.bunifuShadowPanel2.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel2.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel2.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel2.ShadowDept = 2;
            this.bunifuShadowPanel2.ShadowDepth = 5;
            this.bunifuShadowPanel2.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel2.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel2.Size = new System.Drawing.Size(1120, 539);
            this.bunifuShadowPanel2.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel2.TabIndex = 1;
            // 
            // pbImagen
            // 
            this.pbImagen.Location = new System.Drawing.Point(32, 41);
            this.pbImagen.Name = "pbImagen";
            this.pbImagen.Size = new System.Drawing.Size(315, 365);
            this.pbImagen.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbImagen.TabIndex = 3;
            this.pbImagen.TabStop = false;
            // 
            // btnGuardarCambios
            // 
            this.btnGuardarCambios.AllowAnimations = true;
            this.btnGuardarCambios.AllowMouseEffects = true;
            this.btnGuardarCambios.AllowToggling = false;
            this.btnGuardarCambios.AnimationSpeed = 200;
            this.btnGuardarCambios.AutoGenerateColors = false;
            this.btnGuardarCambios.AutoRoundBorders = false;
            this.btnGuardarCambios.AutoSizeLeftIcon = true;
            this.btnGuardarCambios.AutoSizeRightIcon = true;
            this.btnGuardarCambios.BackColor = System.Drawing.Color.Transparent;
            this.btnGuardarCambios.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnGuardarCambios.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGuardarCambios.BackgroundImage")));
            this.btnGuardarCambios.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuardarCambios.ButtonText = "Guardar Cambios";
            this.btnGuardarCambios.ButtonTextMarginLeft = 0;
            this.btnGuardarCambios.ColorContrastOnClick = 45;
            this.btnGuardarCambios.ColorContrastOnHover = 45;
            this.btnGuardarCambios.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnGuardarCambios.CustomizableEdges = borderEdges3;
            this.btnGuardarCambios.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGuardarCambios.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuardarCambios.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGuardarCambios.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGuardarCambios.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnGuardarCambios.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnGuardarCambios.ForeColor = System.Drawing.Color.White;
            this.btnGuardarCambios.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGuardarCambios.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuardarCambios.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnGuardarCambios.IconMarginLeft = 11;
            this.btnGuardarCambios.IconPadding = 10;
            this.btnGuardarCambios.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGuardarCambios.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuardarCambios.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnGuardarCambios.IconSize = 25;
            this.btnGuardarCambios.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnGuardarCambios.IdleBorderRadius = 10;
            this.btnGuardarCambios.IdleBorderThickness = 1;
            this.btnGuardarCambios.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnGuardarCambios.IdleIconLeftImage = null;
            this.btnGuardarCambios.IdleIconRightImage = null;
            this.btnGuardarCambios.IndicateFocus = false;
            this.btnGuardarCambios.Location = new System.Drawing.Point(47, 422);
            this.btnGuardarCambios.Name = "btnGuardarCambios";
            this.btnGuardarCambios.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuardarCambios.OnDisabledState.BorderRadius = 10;
            this.btnGuardarCambios.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuardarCambios.OnDisabledState.BorderThickness = 1;
            this.btnGuardarCambios.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGuardarCambios.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGuardarCambios.OnDisabledState.IconLeftImage = null;
            this.btnGuardarCambios.OnDisabledState.IconRightImage = null;
            this.btnGuardarCambios.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnGuardarCambios.onHoverState.BorderRadius = 10;
            this.btnGuardarCambios.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuardarCambios.onHoverState.BorderThickness = 1;
            this.btnGuardarCambios.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnGuardarCambios.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnGuardarCambios.onHoverState.IconLeftImage = null;
            this.btnGuardarCambios.onHoverState.IconRightImage = null;
            this.btnGuardarCambios.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnGuardarCambios.OnIdleState.BorderRadius = 10;
            this.btnGuardarCambios.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuardarCambios.OnIdleState.BorderThickness = 1;
            this.btnGuardarCambios.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnGuardarCambios.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnGuardarCambios.OnIdleState.IconLeftImage = null;
            this.btnGuardarCambios.OnIdleState.IconRightImage = null;
            this.btnGuardarCambios.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnGuardarCambios.OnPressedState.BorderRadius = 10;
            this.btnGuardarCambios.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuardarCambios.OnPressedState.BorderThickness = 1;
            this.btnGuardarCambios.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnGuardarCambios.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnGuardarCambios.OnPressedState.IconLeftImage = null;
            this.btnGuardarCambios.OnPressedState.IconRightImage = null;
            this.btnGuardarCambios.Size = new System.Drawing.Size(274, 70);
            this.btnGuardarCambios.TabIndex = 19;
            this.btnGuardarCambios.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnGuardarCambios.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnGuardarCambios.TextMarginLeft = 0;
            this.btnGuardarCambios.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnGuardarCambios.UseDefaultRadiusAndThickness = true;
            // 
            // txtNombreCompleto
            // 
            this.txtNombreCompleto.AcceptsReturn = false;
            this.txtNombreCompleto.AcceptsTab = false;
            this.txtNombreCompleto.AnimationSpeed = 200;
            this.txtNombreCompleto.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNombreCompleto.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNombreCompleto.BackColor = System.Drawing.Color.WhiteSmoke;
            this.txtNombreCompleto.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNombreCompleto.BackgroundImage")));
            this.txtNombreCompleto.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNombreCompleto.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNombreCompleto.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNombreCompleto.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNombreCompleto.BorderRadius = 1;
            this.txtNombreCompleto.BorderThickness = 1;
            this.txtNombreCompleto.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNombreCompleto.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombreCompleto.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNombreCompleto.DefaultText = "";
            this.txtNombreCompleto.FillColor = System.Drawing.Color.WhiteSmoke;
            this.txtNombreCompleto.HideSelection = true;
            this.txtNombreCompleto.IconLeft = null;
            this.txtNombreCompleto.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombreCompleto.IconPadding = 10;
            this.txtNombreCompleto.IconRight = null;
            this.txtNombreCompleto.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombreCompleto.Lines = new string[0];
            this.txtNombreCompleto.Location = new System.Drawing.Point(624, 106);
            this.txtNombreCompleto.MaxLength = 32767;
            this.txtNombreCompleto.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNombreCompleto.Modified = false;
            this.txtNombreCompleto.Multiline = false;
            this.txtNombreCompleto.Name = "txtNombreCompleto";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombreCompleto.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNombreCompleto.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombreCompleto.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombreCompleto.OnIdleState = stateProperties4;
            this.txtNombreCompleto.Padding = new System.Windows.Forms.Padding(3);
            this.txtNombreCompleto.PasswordChar = '\0';
            this.txtNombreCompleto.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNombreCompleto.PlaceholderText = "";
            this.txtNombreCompleto.ReadOnly = false;
            this.txtNombreCompleto.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNombreCompleto.SelectedText = "";
            this.txtNombreCompleto.SelectionLength = 0;
            this.txtNombreCompleto.SelectionStart = 0;
            this.txtNombreCompleto.ShortcutsEnabled = true;
            this.txtNombreCompleto.Size = new System.Drawing.Size(256, 37);
            this.txtNombreCompleto.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtNombreCompleto.TabIndex = 23;
            this.txtNombreCompleto.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNombreCompleto.TextMarginBottom = 0;
            this.txtNombreCompleto.TextMarginLeft = 3;
            this.txtNombreCompleto.TextMarginTop = 0;
            this.txtNombreCompleto.TextPlaceholder = "";
            this.txtNombreCompleto.UseSystemPasswordChar = false;
            this.txtNombreCompleto.WordWrap = true;
            // 
            // txtNombreUsuario
            // 
            this.txtNombreUsuario.AcceptsReturn = false;
            this.txtNombreUsuario.AcceptsTab = false;
            this.txtNombreUsuario.AnimationSpeed = 200;
            this.txtNombreUsuario.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNombreUsuario.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNombreUsuario.BackColor = System.Drawing.Color.WhiteSmoke;
            this.txtNombreUsuario.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNombreUsuario.BackgroundImage")));
            this.txtNombreUsuario.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNombreUsuario.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNombreUsuario.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNombreUsuario.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNombreUsuario.BorderRadius = 1;
            this.txtNombreUsuario.BorderThickness = 1;
            this.txtNombreUsuario.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNombreUsuario.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombreUsuario.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNombreUsuario.DefaultText = "";
            this.txtNombreUsuario.FillColor = System.Drawing.Color.WhiteSmoke;
            this.txtNombreUsuario.HideSelection = true;
            this.txtNombreUsuario.IconLeft = null;
            this.txtNombreUsuario.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombreUsuario.IconPadding = 10;
            this.txtNombreUsuario.IconRight = null;
            this.txtNombreUsuario.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombreUsuario.Lines = new string[0];
            this.txtNombreUsuario.Location = new System.Drawing.Point(624, 163);
            this.txtNombreUsuario.MaxLength = 32767;
            this.txtNombreUsuario.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNombreUsuario.Modified = false;
            this.txtNombreUsuario.Multiline = false;
            this.txtNombreUsuario.Name = "txtNombreUsuario";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombreUsuario.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNombreUsuario.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombreUsuario.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombreUsuario.OnIdleState = stateProperties8;
            this.txtNombreUsuario.Padding = new System.Windows.Forms.Padding(3);
            this.txtNombreUsuario.PasswordChar = '\0';
            this.txtNombreUsuario.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNombreUsuario.PlaceholderText = "";
            this.txtNombreUsuario.ReadOnly = false;
            this.txtNombreUsuario.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNombreUsuario.SelectedText = "";
            this.txtNombreUsuario.SelectionLength = 0;
            this.txtNombreUsuario.SelectionStart = 0;
            this.txtNombreUsuario.ShortcutsEnabled = true;
            this.txtNombreUsuario.Size = new System.Drawing.Size(256, 37);
            this.txtNombreUsuario.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtNombreUsuario.TabIndex = 22;
            this.txtNombreUsuario.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNombreUsuario.TextMarginBottom = 0;
            this.txtNombreUsuario.TextMarginLeft = 3;
            this.txtNombreUsuario.TextMarginTop = 0;
            this.txtNombreUsuario.TextPlaceholder = "";
            this.txtNombreUsuario.UseSystemPasswordChar = false;
            this.txtNombreUsuario.WordWrap = true;
            // 
            // txtEmail
            // 
            this.txtEmail.AcceptsReturn = false;
            this.txtEmail.AcceptsTab = false;
            this.txtEmail.AnimationSpeed = 200;
            this.txtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmail.BackColor = System.Drawing.Color.WhiteSmoke;
            this.txtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmail.BackgroundImage")));
            this.txtEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtEmail.BorderRadius = 1;
            this.txtEmail.BorderThickness = 1;
            this.txtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtEmail.DefaultText = "";
            this.txtEmail.FillColor = System.Drawing.Color.WhiteSmoke;
            this.txtEmail.HideSelection = true;
            this.txtEmail.IconLeft = null;
            this.txtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.IconPadding = 10;
            this.txtEmail.IconRight = null;
            this.txtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.Lines = new string[0];
            this.txtEmail.Location = new System.Drawing.Point(624, 228);
            this.txtEmail.MaxLength = 32767;
            this.txtEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmail.Modified = false;
            this.txtEmail.Multiline = false;
            this.txtEmail.Name = "txtEmail";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmail.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnIdleState = stateProperties12;
            this.txtEmail.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmail.PasswordChar = '\0';
            this.txtEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmail.PlaceholderText = "";
            this.txtEmail.ReadOnly = false;
            this.txtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmail.SelectedText = "";
            this.txtEmail.SelectionLength = 0;
            this.txtEmail.SelectionStart = 0;
            this.txtEmail.ShortcutsEnabled = true;
            this.txtEmail.Size = new System.Drawing.Size(256, 37);
            this.txtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtEmail.TabIndex = 21;
            this.txtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmail.TextMarginBottom = 0;
            this.txtEmail.TextMarginLeft = 3;
            this.txtEmail.TextMarginTop = 0;
            this.txtEmail.TextPlaceholder = "";
            this.txtEmail.UseSystemPasswordChar = false;
            this.txtEmail.WordWrap = true;
            // 
            // txtTelefono
            // 
            this.txtTelefono.AcceptsReturn = false;
            this.txtTelefono.AcceptsTab = false;
            this.txtTelefono.AnimationSpeed = 200;
            this.txtTelefono.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTelefono.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTelefono.BackColor = System.Drawing.Color.WhiteSmoke;
            this.txtTelefono.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTelefono.BackgroundImage")));
            this.txtTelefono.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTelefono.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTelefono.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTelefono.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTelefono.BorderRadius = 1;
            this.txtTelefono.BorderThickness = 1;
            this.txtTelefono.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTelefono.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefono.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtTelefono.DefaultText = "";
            this.txtTelefono.FillColor = System.Drawing.Color.WhiteSmoke;
            this.txtTelefono.HideSelection = true;
            this.txtTelefono.IconLeft = null;
            this.txtTelefono.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefono.IconPadding = 10;
            this.txtTelefono.IconRight = null;
            this.txtTelefono.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefono.Lines = new string[0];
            this.txtTelefono.Location = new System.Drawing.Point(624, 290);
            this.txtTelefono.MaxLength = 32767;
            this.txtTelefono.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTelefono.Modified = false;
            this.txtTelefono.Multiline = false;
            this.txtTelefono.Name = "txtTelefono";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefono.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTelefono.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefono.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefono.OnIdleState = stateProperties16;
            this.txtTelefono.Padding = new System.Windows.Forms.Padding(3);
            this.txtTelefono.PasswordChar = '\0';
            this.txtTelefono.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTelefono.PlaceholderText = "";
            this.txtTelefono.ReadOnly = false;
            this.txtTelefono.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTelefono.SelectedText = "";
            this.txtTelefono.SelectionLength = 0;
            this.txtTelefono.SelectionStart = 0;
            this.txtTelefono.ShortcutsEnabled = true;
            this.txtTelefono.Size = new System.Drawing.Size(256, 37);
            this.txtTelefono.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtTelefono.TabIndex = 20;
            this.txtTelefono.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTelefono.TextMarginBottom = 0;
            this.txtTelefono.TextMarginLeft = 3;
            this.txtTelefono.TextMarginTop = 0;
            this.txtTelefono.TextPlaceholder = "";
            this.txtTelefono.UseSystemPasswordChar = false;
            this.txtTelefono.WordWrap = true;
            // 
            // btnEditarClave
            // 
            this.btnEditarClave.AllowAnimations = true;
            this.btnEditarClave.AllowMouseEffects = true;
            this.btnEditarClave.AllowToggling = false;
            this.btnEditarClave.AnimationSpeed = 200;
            this.btnEditarClave.AutoGenerateColors = false;
            this.btnEditarClave.AutoRoundBorders = false;
            this.btnEditarClave.AutoSizeLeftIcon = true;
            this.btnEditarClave.AutoSizeRightIcon = true;
            this.btnEditarClave.BackColor = System.Drawing.Color.Transparent;
            this.btnEditarClave.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnEditarClave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEditarClave.BackgroundImage")));
            this.btnEditarClave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditarClave.ButtonText = "Cambiar Contraseña";
            this.btnEditarClave.ButtonTextMarginLeft = 0;
            this.btnEditarClave.ColorContrastOnClick = 45;
            this.btnEditarClave.ColorContrastOnHover = 45;
            this.btnEditarClave.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnEditarClave.CustomizableEdges = borderEdges4;
            this.btnEditarClave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEditarClave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEditarClave.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEditarClave.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEditarClave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEditarClave.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEditarClave.ForeColor = System.Drawing.Color.White;
            this.btnEditarClave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEditarClave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEditarClave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEditarClave.IconMarginLeft = 11;
            this.btnEditarClave.IconPadding = 10;
            this.btnEditarClave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEditarClave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEditarClave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEditarClave.IconSize = 25;
            this.btnEditarClave.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnEditarClave.IdleBorderRadius = 10;
            this.btnEditarClave.IdleBorderThickness = 1;
            this.btnEditarClave.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnEditarClave.IdleIconLeftImage = null;
            this.btnEditarClave.IdleIconRightImage = null;
            this.btnEditarClave.IndicateFocus = false;
            this.btnEditarClave.Location = new System.Drawing.Point(537, 368);
            this.btnEditarClave.Name = "btnEditarClave";
            this.btnEditarClave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEditarClave.OnDisabledState.BorderRadius = 10;
            this.btnEditarClave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditarClave.OnDisabledState.BorderThickness = 1;
            this.btnEditarClave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEditarClave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEditarClave.OnDisabledState.IconLeftImage = null;
            this.btnEditarClave.OnDisabledState.IconRightImage = null;
            this.btnEditarClave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEditarClave.onHoverState.BorderRadius = 10;
            this.btnEditarClave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditarClave.onHoverState.BorderThickness = 1;
            this.btnEditarClave.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEditarClave.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEditarClave.onHoverState.IconLeftImage = null;
            this.btnEditarClave.onHoverState.IconRightImage = null;
            this.btnEditarClave.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnEditarClave.OnIdleState.BorderRadius = 10;
            this.btnEditarClave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditarClave.OnIdleState.BorderThickness = 1;
            this.btnEditarClave.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnEditarClave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEditarClave.OnIdleState.IconLeftImage = null;
            this.btnEditarClave.OnIdleState.IconRightImage = null;
            this.btnEditarClave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEditarClave.OnPressedState.BorderRadius = 10;
            this.btnEditarClave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditarClave.OnPressedState.BorderThickness = 1;
            this.btnEditarClave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEditarClave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEditarClave.OnPressedState.IconLeftImage = null;
            this.btnEditarClave.OnPressedState.IconRightImage = null;
            this.btnEditarClave.Size = new System.Drawing.Size(162, 38);
            this.btnEditarClave.TabIndex = 19;
            this.btnEditarClave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEditarClave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEditarClave.TextMarginLeft = 0;
            this.btnEditarClave.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEditarClave.UseDefaultRadiusAndThickness = true;
            this.btnEditarClave.Click += new System.EventHandler(this.btnEditarClave_Click);
            // 
            // btnEditarUsuario
            // 
            this.btnEditarUsuario.AllowAnimations = true;
            this.btnEditarUsuario.AllowMouseEffects = true;
            this.btnEditarUsuario.AllowToggling = false;
            this.btnEditarUsuario.AnimationSpeed = 200;
            this.btnEditarUsuario.AutoGenerateColors = false;
            this.btnEditarUsuario.AutoRoundBorders = false;
            this.btnEditarUsuario.AutoSizeLeftIcon = true;
            this.btnEditarUsuario.AutoSizeRightIcon = true;
            this.btnEditarUsuario.BackColor = System.Drawing.Color.Transparent;
            this.btnEditarUsuario.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnEditarUsuario.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEditarUsuario.BackgroundImage")));
            this.btnEditarUsuario.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditarUsuario.ButtonText = "Editar Usuario";
            this.btnEditarUsuario.ButtonTextMarginLeft = 0;
            this.btnEditarUsuario.ColorContrastOnClick = 45;
            this.btnEditarUsuario.ColorContrastOnHover = 45;
            this.btnEditarUsuario.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnEditarUsuario.CustomizableEdges = borderEdges5;
            this.btnEditarUsuario.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEditarUsuario.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEditarUsuario.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEditarUsuario.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEditarUsuario.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEditarUsuario.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEditarUsuario.ForeColor = System.Drawing.Color.White;
            this.btnEditarUsuario.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEditarUsuario.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEditarUsuario.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEditarUsuario.IconMarginLeft = 11;
            this.btnEditarUsuario.IconPadding = 10;
            this.btnEditarUsuario.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEditarUsuario.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEditarUsuario.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEditarUsuario.IconSize = 25;
            this.btnEditarUsuario.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnEditarUsuario.IdleBorderRadius = 10;
            this.btnEditarUsuario.IdleBorderThickness = 1;
            this.btnEditarUsuario.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnEditarUsuario.IdleIconLeftImage = null;
            this.btnEditarUsuario.IdleIconRightImage = null;
            this.btnEditarUsuario.IndicateFocus = false;
            this.btnEditarUsuario.Location = new System.Drawing.Point(914, 163);
            this.btnEditarUsuario.Name = "btnEditarUsuario";
            this.btnEditarUsuario.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEditarUsuario.OnDisabledState.BorderRadius = 10;
            this.btnEditarUsuario.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditarUsuario.OnDisabledState.BorderThickness = 1;
            this.btnEditarUsuario.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEditarUsuario.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEditarUsuario.OnDisabledState.IconLeftImage = null;
            this.btnEditarUsuario.OnDisabledState.IconRightImage = null;
            this.btnEditarUsuario.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEditarUsuario.onHoverState.BorderRadius = 10;
            this.btnEditarUsuario.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditarUsuario.onHoverState.BorderThickness = 1;
            this.btnEditarUsuario.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEditarUsuario.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEditarUsuario.onHoverState.IconLeftImage = null;
            this.btnEditarUsuario.onHoverState.IconRightImage = null;
            this.btnEditarUsuario.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnEditarUsuario.OnIdleState.BorderRadius = 10;
            this.btnEditarUsuario.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditarUsuario.OnIdleState.BorderThickness = 1;
            this.btnEditarUsuario.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnEditarUsuario.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEditarUsuario.OnIdleState.IconLeftImage = null;
            this.btnEditarUsuario.OnIdleState.IconRightImage = null;
            this.btnEditarUsuario.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEditarUsuario.OnPressedState.BorderRadius = 10;
            this.btnEditarUsuario.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditarUsuario.OnPressedState.BorderThickness = 1;
            this.btnEditarUsuario.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEditarUsuario.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEditarUsuario.OnPressedState.IconLeftImage = null;
            this.btnEditarUsuario.OnPressedState.IconRightImage = null;
            this.btnEditarUsuario.Size = new System.Drawing.Size(162, 38);
            this.btnEditarUsuario.TabIndex = 18;
            this.btnEditarUsuario.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEditarUsuario.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEditarUsuario.TextMarginLeft = 0;
            this.btnEditarUsuario.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEditarUsuario.UseDefaultRadiusAndThickness = true;
            this.btnEditarUsuario.Click += new System.EventHandler(this.btnEditarUsuario_Click);
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel9.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel9.Font = new System.Drawing.Font("Segoe UI", 18F);
            this.bunifuLabel9.Location = new System.Drawing.Point(373, 368);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(120, 32);
            this.bunifuLabel9.TabIndex = 14;
            this.bunifuLabel9.Text = "Contraseña";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel8.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel8.Font = new System.Drawing.Font("Segoe UI", 18F);
            this.bunifuLabel8.Location = new System.Drawing.Point(373, 295);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(229, 32);
            this.bunifuLabel8.TabIndex = 10;
            this.bunifuLabel8.Text = "Numero de Teléfono:";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 18F);
            this.bunifuLabel5.Location = new System.Drawing.Point(373, 233);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(73, 32);
            this.bunifuLabel5.TabIndex = 9;
            this.bunifuLabel5.Text = "E-Mail:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel7.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI", 18F);
            this.bunifuLabel7.Location = new System.Drawing.Point(373, 168);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(214, 32);
            this.bunifuLabel7.TabIndex = 8;
            this.bunifuLabel7.Text = "Nombre de Usuario:";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 18F);
            this.bunifuLabel6.Location = new System.Drawing.Point(373, 106);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(205, 32);
            this.bunifuLabel6.TabIndex = 7;
            this.bunifuLabel6.Text = "Nombre Completo:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblUltimoAcceso
            // 
            this.lblUltimoAcceso.AllowParentOverrides = false;
            this.lblUltimoAcceso.AutoEllipsis = false;
            this.lblUltimoAcceso.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblUltimoAcceso.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblUltimoAcceso.Font = new System.Drawing.Font("Segoe UI", 18F);
            this.lblUltimoAcceso.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.lblUltimoAcceso.Location = new System.Drawing.Point(750, 41);
            this.lblUltimoAcceso.Name = "lblUltimoAcceso";
            this.lblUltimoAcceso.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblUltimoAcceso.Size = new System.Drawing.Size(40, 32);
            this.lblUltimoAcceso.TabIndex = 5;
            this.lblUltimoAcceso.Text = "null";
            this.lblUltimoAcceso.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblUltimoAcceso.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 18F);
            this.bunifuLabel3.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.bunifuLabel3.Location = new System.Drawing.Point(577, 41);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(154, 32);
            this.bunifuLabel3.TabIndex = 4;
            this.bunifuLabel3.Text = "Ultimo acceso:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI Semibold", 18F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.Location = new System.Drawing.Point(373, 41);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(165, 32);
            this.bunifuLabel2.TabIndex = 3;
            this.bunifuLabel2.Text = "Mi información";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.BorderRadius = 10;
            this.bunifuShadowPanel1.BorderThickness = 1;
            this.bunifuShadowPanel1.Controls.Add(this.pictureBox1);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(12, 12);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 5;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(375, 106);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 0;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = global::PrintTrack.Properties.Resources.person;
            this.pictureBox1.Location = new System.Drawing.Point(32, 15);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(86, 79);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 2;
            this.pictureBox1.TabStop = false;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Semibold", 27.75F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.Location = new System.Drawing.Point(129, 27);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(143, 50);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Mi Perfil";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Perfil_Frm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1144, 675);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.Name = "Perfil_Frm";
            this.Text = "Perfil_Frm";
            this.Load += new System.EventHandler(this.Perfil_Frm_Load);
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuShadowPanel3.ResumeLayout(false);
            this.bunifuShadowPanel2.ResumeLayout(false);
            this.bunifuShadowPanel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbImagen)).EndInit();
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel2;
        private System.Windows.Forms.PictureBox pbImagen;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel lblUltimoAcceso;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnIniciarTurno;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEditarUsuario;
        private Bunifu.UI.WinForms.BunifuTextBox txtNombreCompleto;
        private Bunifu.UI.WinForms.BunifuTextBox txtNombreUsuario;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmail;
        private Bunifu.UI.WinForms.BunifuTextBox txtTelefono;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEditarClave;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnFinTurno;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnGuardarCambios;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
    }
}